// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddfhwkynydqhqeyifeta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZmh3a3lueWRxaHFleWlmZXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MzM3MTksImV4cCI6MjA5MTIwOTcxOX0.WWMvCnoKMOfQo_xLwXahehg6jX7PrxFWRZgwp12T1pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});